/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;
import Backend.Student;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author DELL
 */
public class StudentDashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboardFrame
     */
    private Student currentStudent;
    public StudentDashboardFrame(Student currentStudent) {
        
        this.currentStudent=currentStudent;
        initComponents();
        
        BrowseCourses bc = new BrowseCourses(currentStudent);
        
      //  ViewLessons vl = new ViewLessons(); /////fe moshkla hena, anhe course?
        JTabbedPane tabs = new JTabbedPane();
        ViewEnrolledCourses vnc = new ViewEnrolledCourses(currentStudent,tabs);
        tabs.addTab("Browse Courses", bc);
        tabs.addTab("View Enrolled Courses",vnc);
          tabs.addTab("View Lessons", new JPanel());
        getContentPane().setLayout(new BorderLayout());
         getContentPane().add(tabs, BorderLayout.CENTER);

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
