
package Frontend;
import Backend.Students;
import Backend.Course;
import Backend.jsonFile;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author DELL
 */
public class BrowseCourses extends javax.swing.JPanel {

   private Students currentStudent;
   private JPanel createCourseBox(String title, String desc, Course course){
   JPanel panel = new JPanel();
   panel.setLayout(new BorderLayout());
   panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 80));
   panel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));
   JPanel textPanel = new JPanel();
   textPanel.setLayout(new BoxLayout(textPanel, BoxLayout.Y_AXIS));
   JLabel name = new JLabel(title);
   name.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 20));
   
   JLabel description = new JLabel(desc);
   textPanel.add(name);
   textPanel.add(Box.createRigidArea(new Dimension(0,20)));
   textPanel.add(description);
   panel.add(textPanel, BorderLayout.CENTER);
   JPanel buttonPanel = new JPanel(new BorderLayout());
   
   JButton enroll = new JButton("Enroll");
//   enroll.setAlignmentX(java.awt.Component.RIGHT_ALIGNMENT);

   enroll.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
   course.enrollInCourse(currentStudent);
   jsonFile.SAVE();
   enroll.setEnabled(false);
    }
    });
   if(currentStudent.checkifEnrolled(course.getCourseId())){{
       enroll.setEnabled(false);
   }}
   buttonPanel.add(enroll, BorderLayout.NORTH);
   panel.add(buttonPanel, BorderLayout.EAST);
   //panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10,10,10,10));
   return panel;
}


    public BrowseCourses(Students currentStudent) {

         this.currentStudent=currentStudent;
      initComponents();

        coursePanelMain.setVisible(false);

        try {

   ArrayList <Course>coursesArray = jsonFile.getAllCourses();
   JPanel coursesCONT = new JPanel();
   coursesCONT.setLayout(new BoxLayout(coursesCONT,BoxLayout.Y_AXIS));
   for(Course c : coursesArray){
    JPanel card = createCourseBox(c.getTitle(), c.getDescription(), c);
    card.setAlignmentX(Component.LEFT_ALIGNMENT);
    card.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
    coursesCONT.add(card);
    coursesCONT.add(javax.swing.Box.createVerticalStrut(10));
   }
   JScrollPane scroll = new JScrollPane(coursesCONT);
   scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
   this.add(scroll,java.awt.BorderLayout.CENTER);

        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,"FAILED TO LOAD COURSES!");
        
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        viewcourses = new javax.swing.JLabel();
        coursePanelMain = new javax.swing.JPanel();
        courseName = new javax.swing.JLabel();
        courseDescription = new javax.swing.JLabel();
        enrollbutton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        viewcourses.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 36)); // NOI18N
        viewcourses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewcourses.setText("View Courses");
        viewcourses.setMaximumSize(new java.awt.Dimension(50, 45));
        viewcourses.setMinimumSize(new java.awt.Dimension(40, 45));
        viewcourses.setPreferredSize(new java.awt.Dimension(50, 45));
        add(viewcourses, java.awt.BorderLayout.NORTH);

        coursePanelMain.setBorder(new javax.swing.border.MatteBorder(null));

        courseName.setText("Course Name");

        courseDescription.setText("Course Description");

        enrollbutton.setText("Enroll");
        enrollbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coursePanelMainLayout = new javax.swing.GroupLayout(coursePanelMain);
        coursePanelMain.setLayout(coursePanelMainLayout);
        coursePanelMainLayout.setHorizontalGroup(
            coursePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelMainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(coursePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelMainLayout.createSequentialGroup()
                        .addComponent(courseName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(coursePanelMainLayout.createSequentialGroup()
                        .addComponent(courseDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 630, Short.MAX_VALUE)
                        .addComponent(enrollbutton)
                        .addGap(39, 39, 39))))
        );
        coursePanelMainLayout.setVerticalGroup(
            coursePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelMainLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(courseName)
                .addGroup(coursePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelMainLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(courseDescription)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursePanelMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enrollbutton)
                        .addGap(22, 22, 22))))
        );

        add(coursePanelMain, java.awt.BorderLayout.PAGE_END);
    }//GEN-END:initComponents

    private void enrollbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollbuttonActionPerformed
      
    }//GEN-LAST:event_enrollbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseDescription;
    private javax.swing.JLabel courseName;
    private javax.swing.JPanel coursePanelMain;
    private javax.swing.JButton enrollbutton;
    private javax.swing.JLabel viewcourses;
    // End of variables declaration//GEN-END:variables
//}
//class TestBrowseCourses {
//public static void main(String[] args){
//javax.swing.SwingUtilities.invokeLater(new Runnable(){
//public void run(){
//    jsonFile j = new jsonFile();
//byte[] ph = new byte[]{1,2,3};
//byte[] sa = new byte[]{4,5,6};
//Backend.Students s = new Backend.Students("testuser","test@mail.com",ph,sa);
//
//javax.swing.JFrame f = new javax.swing.JFrame("Test Browse Courses");
//f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
//f.setSize(900,600);
//f.add(new Frontend.BrowseCourses(s));
//f.setVisible(true);
//}
//});
//}
}
