
package Frontend;

import Backend.Course;
import Backend.Enrollment;
import Backend.jsonFile;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author DELL
 */
public class BrowseCourses extends javax.swing.JPanel {

    
    public BrowseCourses() {
      initComponents();
        coursePanelMain.setVisible(false);
        JPanel coursesScroll = new JPanel();
        coursesScroll.setLayout(new BoxLayout(coursesScroll, BoxLayout.Y_AXIS));
        JScrollPane scrollPane = new JScrollPane(coursesScroll);
    this.add(scrollPane); 
        try {
            
        ArrayList<Course> coursesArray = jsonFile.getAllCourses();
        
        for (int i = 0; i < coursesArray.size(); i++) {
        
            
           Course course = coursesArray.get(i);
           JPanel panel = new JPanel();
           panel.setLayout(coursePanelMain.getLayout());
        
           JLabel courseName = new JLabel (course.getTitle());
           JLabel coursedescription = new JLabel (course.getDescription());
           JButton button = new JButton("Enroll");
           button.addActionListener(new ActionListener() {
                   public void actionPerformed(ActionEvent evt) {
                       
                       
              
                   }});
        
        
        panel.add(courseName);
        panel.add(coursedescription);
        panel.add(button);
        coursesScroll.add(panel);

        }
           
       
        coursesScroll.revalidate();
        coursesScroll.repaint();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"FAILED TO LOAD COURSES!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewcourses = new javax.swing.JLabel();
        coursePanelMain = new javax.swing.JPanel();
        courseName = new javax.swing.JLabel();
        courseDescription = new javax.swing.JLabel();
        enrollbutton = new javax.swing.JButton();

        viewcourses.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 36)); // NOI18N
        viewcourses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewcourses.setText("View Courses");

        coursePanelMain.setBorder(new javax.swing.border.MatteBorder(null));

        courseName.setText("Course Name");

        courseDescription.setText("Course Description");

        enrollbutton.setText("Enroll");
        enrollbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coursePanelMainLayout = new javax.swing.GroupLayout(coursePanelMain);
        coursePanelMain.setLayout(coursePanelMainLayout);
        coursePanelMainLayout.setHorizontalGroup(
            coursePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelMainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(coursePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelMainLayout.createSequentialGroup()
                        .addComponent(courseName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(coursePanelMainLayout.createSequentialGroup()
                        .addComponent(courseDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 561, Short.MAX_VALUE)
                        .addComponent(enrollbutton)
                        .addGap(39, 39, 39))))
        );
        coursePanelMainLayout.setVerticalGroup(
            coursePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelMainLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(courseName)
                .addGroup(coursePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelMainLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(courseDescription)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursePanelMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enrollbutton)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewcourses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(coursePanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(viewcourses)
                .addGap(29, 29, 29)
                .addComponent(coursePanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enrollbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollbuttonActionPerformed
       //temporary hard codes for the studentID and courseID
        int studentID=1000;
        int courseID=1;
        
        Enrollment enroll = new Enrollment();
        
        enroll.enrollstudentincourse(courseID,studentID);
    }//GEN-LAST:event_enrollbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseDescription;
    private javax.swing.JLabel courseName;
    private javax.swing.JPanel coursePanelMain;
    private javax.swing.JButton enrollbutton;
    private javax.swing.JLabel viewcourses;
    // End of variables declaration//GEN-END:variables
}
