/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frontend;

import Backend.Certificate;
import Backend.StudentProgressInCourse;
import Backend.Students;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class CertificateReport extends javax.swing.JDialog {

    /**
     * Creates new form CertificateReport
     */
    private ArrayList<Certificate> certificates;
     Certificate c = null;
     public CertificateReport()
     {
         initComponents();
     }

    public CertificateReport(java.awt.Frame parent, boolean modal, Students currentStudent,StudentProgressInCourse spic) {
        super(parent, modal);
        initComponents();
        c = loadCertificate(currentStudent,spic);
        if(c!=null)
        {
        issueDateTXT.setText(c.getIssuedate().toString());
        studentIdTXT.setText(c.getStudentId());
          courseIdTXT.setText(c.getCourseId());
        certificateIdTXT.setText(c.getCertificateId());
        }
        else{
           JOptionPane.showMessageDialog(null, "ERROR NO CERTIFICATES FOUND!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
     
    public Certificate loadCertificate(Students currentStudent,StudentProgressInCourse spic)
    {
     
        for (Certificate cert : currentStudent.getCertificatesEarned()) 
        {
            if (cert.getCourseId().equals(spic.getCourseId())) {
                   return cert;
    }} return null;
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseIdLABEL = new javax.swing.JLabel();
        studentIdLABEL = new javax.swing.JLabel();
        issueDateLABEL = new javax.swing.JLabel();
        certificateIdLABEL = new javax.swing.JLabel();
        courseIdTXT = new javax.swing.JLabel();
        studentIdTXT = new javax.swing.JLabel();
        issueDateTXT = new javax.swing.JLabel();
        certificateIdTXT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        courseIdLABEL.setText("Course ID:");

        studentIdLABEL.setText("Student ID");

        issueDateLABEL.setText("Issue Date:");

        certificateIdLABEL.setText("Certificate ID: ");

        courseIdTXT.setText("jLabel4");

        studentIdTXT.setText("jLabel5");

        issueDateTXT.setText("jLabel6");

        certificateIdTXT.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(studentIdLABEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(courseIdLABEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(issueDateLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certificateIdLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueDateTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certificateIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(courseIdLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(courseIdTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueDateLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueDateTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certificateIdLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certificateIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel certificateIdLABEL;
    private javax.swing.JLabel certificateIdTXT;
    private javax.swing.JLabel courseIdLABEL;
    private javax.swing.JLabel courseIdTXT;
    private javax.swing.JLabel issueDateLABEL;
    private javax.swing.JLabel issueDateTXT;
    private javax.swing.JLabel studentIdLABEL;
    private javax.swing.JLabel studentIdTXT;
    // End of variables declaration//GEN-END:variables
}
