/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;
import Backend.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author DELL
 */
public class CertificateView extends javax.swing.JPanel {

    /**
     * Creates new form CertificateView
     */
    Students currentStudent;
    public CertificateView(Students currentStudent) {
        initComponents();
        this.currentStudent=currentStudent;
       
        
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for (StudentProgressInCourse c : currentStudent.getEnrolledCourses()) {
            
            model.addElement(c.getCourseId());
        }
        listOfCertificates.setModel(model);
        
        
        listOfCertificates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                 if (evt.getClickCount() == 2) {
                   int index = listOfCertificates.locationToIndex(evt.getPoint());
                   String courseID = listOfCertificates.getModel().getElementAt(index);
  
                   ArrayList < Certificate >  certificates = currentStudent.getCertificatesEarned();
                   
                   StudentProgressInCourse selectedCourse = null;
                     for (StudentProgressInCourse c : currentStudent.getEnrolledCourses()) {
                       if (c.getCourseId().equals(courseID)) {
                          selectedCourse = c;
                          break;
                          }
                      }
                   if(selectedCourse!=null)
                {
                    
                   CertificateReport dialog = new CertificateReport(null, true,currentStudent,selectedCourse);
                   dialog.setLocationRelativeTo(null);
                   dialog.setVisible(true);
                }
                   else
                {
                    JOptionPane.showMessageDialog(null, "ERROR!!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                  }
                }
              });
        
        
        
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        certificateTXT = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfCertificates = new javax.swing.JList<>();
        extraTXT = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        certificateTXT.setFont(new java.awt.Font("Dutch801 XBd BT", 3, 48)); // NOI18N
        certificateTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certificateTXT.setText("Certificate View!");

        listOfCertificates.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Course 1 (Sorry, no certificate AS A MESSAGE)", "Course 2", "Course 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listOfCertificates);

        extraTXT.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        extraTXT.setText("You can only view your certificates here as a digital copy, to download please press the download buttont!");

        jButton1.setText("Download");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(certificateTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(extraTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(certificateTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extraTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int index = listOfCertificates.getSelectedIndex();
        if (index == -1)
        {
            JOptionPane.showMessageDialog(this, "Choose a course first to download!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String courseId = listOfCertificates.getModel().getElementAt(index);
        
        ArrayList<Certificate> certificatesAll = currentStudent.getCertificatesEarned();
        Certificate wanted = null;

        for (Certificate certificate : certificatesAll) 
        {
            if(certificate.getCourseId().equals(courseId))
            {
                wanted = certificate;
                break;
            }
        }
        
        if(wanted == null )
        {
            JOptionPane.showMessageDialog(this, "NO CERTIFICATES FOUND IN THIS COURSE FOR YOU!!", "Error", JOptionPane.ERROR_MESSAGE); //ll student DAAA
            return;
        }
        CertificatePDF certpdf = new CertificatePDF(wanted.getCertificateId(),wanted.getStudentId(),wanted.getCourseId(),wanted.getIssuedate().toString());
        try {
        String filename = "Certificates/Certificate_" + courseId + ".pdf";
        certpdf.generatePDF(filename); 
        JOptionPane.showMessageDialog(this, "Downloaded as: " + filename);
          } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "ERROR IN DOWNLOADING! try again...", "Error", JOptionPane.ERROR_MESSAGE);
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel certificateTXT;
    private javax.swing.JLabel extraTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOfCertificates;
    // End of variables declaration//GEN-END:variables
}
