/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frontend;
import Backend.QuizManager;
import Backend.CourseQuizProgress;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;


/**
 *
 * @author LapTop
 */
public class ChartDialog extends javax.swing.JDialog {
     
    private String courseId;
    private QuizManager quizManager; 
   
    public ChartDialog (JFrame parent, String courseId, QuizManager quizManager) {
        super(parent, "Course Insights", true); 
        this.courseId = courseId;
        this.quizManager = quizManager;

        setSize(800, 600);
        setLocationRelativeTo(parent);

        JTabbedPane tabs = new JTabbedPane();
        tabs.add("Score Distribution", createScoreDistributionPanel());
        tabs.add("Quiz Averages", createQuizAveragePanel());
        tabs.add("Completion %", createCompletionPanel());

        add(tabs);
    }
  private JPanel createScoreDistributionPanel() {
    JPanel panel = new JPanel(new BorderLayout());
    CourseQuizProgress courseProg = quizManager.getCourseProgress().get(courseId);

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    if (courseProg != null) {
        ArrayList<String> quizIds = courseProg.getAllQuizIds();
        for (String quizId : quizIds) {
            ArrayList<Integer> scores = courseProg.getQuizScores(quizId);
            HashMap<Integer, Integer> scoreCount = new HashMap<>();
            for (int score : scores) {
                scoreCount.put(score, scoreCount.getOrDefault(score, 0) + 1);
            }
            for (int s : scoreCount.keySet()) {
                dataset.addValue(scoreCount.get(s), quizId, String.valueOf(s) );
            }
        }
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Score Distribution",
            "Score",
            "Number of Students",
            dataset,
            PlotOrientation.VERTICAL,
            true, true, false
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    panel.add(chartPanel, BorderLayout.CENTER);
    return panel;
}
 private JPanel createQuizAveragePanel() {
        JPanel panel = new JPanel(new BorderLayout());
        CourseQuizProgress courseProg = quizManager.getCourseProgress().get(courseId);

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        if (courseProg != null) {
            ArrayList<String> quizIds = new ArrayList<>(courseProg.getAllQuizIds());
            for (String quizId : quizIds) {
                double avg = quizManager.getCourseQuizAvrg(courseId, quizId);
                dataset.addValue(avg, "Average Score", quizId);
            }
        }

        JFreeChart chart = ChartFactory.createLineChart(
                "Quiz Averages",
                "Quiz",
                "Average Score",
                dataset,
                PlotOrientation.VERTICAL,
                false, true, false
        );

        ChartPanel chartPanel = new ChartPanel(chart);
        panel.add(chartPanel, BorderLayout.CENTER);
        return panel;
    }
  private JPanel createCompletionPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        CourseQuizProgress courseProg = quizManager.getCourseProgress().get(courseId);

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        if (courseProg != null) {
            ArrayList<String> quizIds = new ArrayList<>(courseProg.getAllQuizIds());
            for (String quizId : quizIds) {
                int completed = quizManager.getCourseCompleteCount(courseId, quizId);
                dataset.addValue(completed, "Completed Students", quizId);
            }
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Completion Percentage",
                "Quiz",
                "Number of Students Completed",
                dataset,
                PlotOrientation.VERTICAL,
                false, true, false
        );

        ChartPanel chartPanel = new ChartPanel(chart);
        panel.add(chartPanel, BorderLayout.CENTER);
        return panel;
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChartDialog.class.getName());

    /**
     * Creates new form ChartDialog
     */
    public ChartDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChartDialog dialog = new ChartDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
