/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frontend;
import Backend.Course;
import Backend.Instructor;
import Backend.Students;
import Backend.jsonFile;

import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author LapTop
 */
public class CreateCourseDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateCourseDialog.class.getName());
private Students currentStudent;
private Instructor currentInstructor;
    /**
     * Creates new form CreateCourseDialog
     */
    public CreateCourseDialog(java.awt.Frame parent, boolean modal,Instructor instructor) {
        super(parent, modal);
        this.currentInstructor = instructor;
        initComponents();
        AddLessons.setVisible(false);
        CreateBtn.setVisible(true);
//        addCreateButton();
        
    }
//    private void addCreateButton() {
//        JButton createBtn = new JButton("Create Course");
//        jPanel1.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 150, 30));
//
//    
//    }
    
    public void StudentDashboardFrame(Students currentStudent) {
        
        this.currentStudent=currentStudent;
        initComponents();
        
        BrowseCourses bc = new BrowseCourses(currentStudent);
        
      //  ViewLessons vl = new ViewLessons(); /////fe moshkla hena, anhe course?
        JTabbedPane tabs = new JTabbedPane();
        ViewEnrolledCourses vnc = new ViewEnrolledCourses(currentStudent,tabs);
        tabs.addTab("Browse Courses", bc);
        tabs.addTab("View Enrolled Courses",vnc);
          tabs.addTab("View Lessons", new JPanel());
        getContentPane().setLayout(new BorderLayout());
         getContentPane().add(tabs, BorderLayout.CENTER);

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        DesTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CreateBtn = new javax.swing.JButton();
        AddLessons = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE COURSE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Course Title");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 78, 20));

        titleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtActionPerformed(evt);
            }
        });
        jPanel1.add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 250, -1));
        jPanel1.add(DesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 250, 30));

        jLabel4.setText("Course Description");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, -1));

        CreateBtn.setText("CREATE COURSE");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CreateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 170, -1));

        AddLessons.setText("ADD LESSONS");
        jPanel1.add(AddLessons, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void titleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtActionPerformed

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
         String title = titleTxt.getText().trim();
        String description = DesTxt.getText().trim();
        if (title.isEmpty() || description.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Title and description cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        Course newCourse = jsonFile.CreateCourse(currentInstructor.getId(), title, description);
        if (newCourse != null) {
            JOptionPane.showMessageDialog(this, "Course created successfully!");
            AddLessons.setVisible(true);
            CreateBtn.setVisible(false);
            AddLessons.addActionListener(ev -> {
            Edit_Addlesson addLessonDialog = new Edit_Addlesson(null, true, currentInstructor, newCourse, null, false);
            addLessonDialog.setVisible(true);
            
            });
    }//GEN-LAST:event_CreateBtnActionPerformed
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                CreateCourseDialog dialog = new CreateCourseDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLessons;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JTextField DesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
