/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;
import Backend.Course;
import Backend.Instructor;
import Backend.InstructorCourseManager;
import Backend.StudentProgressInCourse;
import java.util.ArrayList;
import Backend.Students;
import Backend.jsonFile;
import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JList;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LapTop
 */
public class InstructorDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InstructorDashboard.class.getName());
private Instructor ins;
jsonFile coursesDb=new jsonFile();
    /**
     * Creates new form InstructorDashboard
     */
    public InstructorDashboard(Instructor ins) {
        this.ins  = ins;
        initComponents(); 
        courseTable.setDefaultEditor(Object.class, null);
        LOADTable();
        actionpanel.setVisible(false); // hide the panel l7ad ma course ykon selected
        courseTable.addMouseListener(new java.awt.event.MouseAdapter() //lama ndos double click panel yban
        {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            if (e.getClickCount() == 2) { // double click
                int selectedRow = courseTable.getSelectedRow();
                if (selectedRow != -1) {
                    actionpanel.setVisible(true); // show panel
                }
            }
        }
    });
    }
   private void LOADTable(){
   DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
   model.setRowCount(0); 
   for(Course c : jsonFile.getAllCourses()){
       System.err.println(c.getTitle());
   if(c.getInstructorId().equals(ins.getId())){
   model.addRow(new Object[]{
   c.getTitle(),
       
       c.getCourseId(),
           c.getDescription(),
           c.getStatus().toUpperCase()
   
   });
   }
   }
   
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreateCourse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        actionpanel = new javax.swing.JPanel();
        editCourse = new javax.swing.JButton();
        deleteCourse = new javax.swing.JButton();
        viewStudent = new javax.swing.JButton();
        manageLessonsBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateCourse.setText("Create course");
        CreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 371, Short.MAX_VALUE)
                .addComponent(CreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "ID", "Description", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(courseTable);

        javax.swing.GroupLayout actionpanelLayout = new javax.swing.GroupLayout(actionpanel);
        actionpanel.setLayout(actionpanelLayout);
        actionpanelLayout.setHorizontalGroup(
            actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        actionpanelLayout.setVerticalGroup(
            actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        editCourse.setText("Edit course");
        editCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCourseActionPerformed(evt);
            }
        });

        deleteCourse.setText("Delete course");
        deleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseActionPerformed(evt);
            }
        });

        viewStudent.setText("View students");
        viewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentActionPerformed(evt);
            }
        });

        manageLessonsBtn.setText("Manage lessons");
        manageLessonsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLessonsBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(actionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageLessonsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewStudent)
                    .addComponent(manageLessonsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCourseActionPerformed
       int selectedRow = courseTable.getSelectedRow();
    if (selectedRow != -1) {
        String courseId = courseTable.getValueAt(selectedRow, 1).toString();
        String currentTitle = courseTable.getValueAt(selectedRow, 0).toString();
        String currentDesc = courseTable.getValueAt(selectedRow, 2).toString();

        String newTitle = JOptionPane.showInputDialog(this, "Edit Title:", currentTitle);
        String newDesc = JOptionPane.showInputDialog(this, "Edit Description:", currentDesc);

        if (newTitle != null && newDesc != null) {
            jsonFile.updatecourse(ins.getId(), courseId, newTitle, newDesc);
            courseTable.setValueAt(newTitle, selectedRow, 0);
            courseTable.setValueAt(newDesc, selectedRow, 2);
        }
    }
    }//GEN-LAST:event_editCourseActionPerformed

    private void deleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseActionPerformed
     int selectedRow = courseTable.getSelectedRow();
    if (selectedRow != -1) {
        String courseId = courseTable.getValueAt(selectedRow, 1).toString(); // ID column
        int confirm = JOptionPane.showConfirmDialog(this, 
                        "Are you sure you want to delete this course?", 
                        "Confirm Delete", 
                        JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            jsonFile.DeleteCourse(courseId,ins.getId());
          
            ((DefaultTableModel)courseTable.getModel()).removeRow(selectedRow);
            ArrayList<Students> students = jsonFile.getAllStudentinCourse(courseId); 
            for (int i = 0 ; i < students.size() ; i++)
            {
            ArrayList<StudentProgressInCourse> enrolledCourses = students.get(i).getEnrolledCourses();
            
                for (int j = 0; j < enrolledCourses.size(); j++)
            {
            if (enrolledCourses.get(j).getCourseId().equals(courseId))
            {
                enrolledCourses.remove(j);
                break; // done
            }
        }
  
            }
    
            actionpanel.setVisible(false);
            jsonFile.SAVE();
        }
    }
    }//GEN-LAST:event_deleteCourseActionPerformed

    private void viewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentActionPerformed

    int selectedRow = courseTable.getSelectedRow();
    if (selectedRow != -1) {
        String courseId = courseTable.getValueAt(selectedRow, 1).toString(); 
        ArrayList<Students> students = jsonFile.getAllStudentinCourse(courseId); 

        StudentListDialog dlg = new StudentListDialog(this, true); 
        dlg.setStudents(students);
        dlg.setVisible(true);
    }
    }//GEN-LAST:event_viewStudentActionPerformed

    private void CreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCourseActionPerformed
        // TODO add your handling code here:
 
        CreateCourseDialog dialog = new CreateCourseDialog(InstructorDashboard.this, true,ins);
        dialog.setLocationRelativeTo(InstructorDashboard.this);
        dialog.setVisible(true);
        LOADTable();
        
    
    }//GEN-LAST:event_CreateCourseActionPerformed

    private void manageLessonsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLessonsBtnActionPerformed
        int selectedRow=courseTable.getSelectedRow();
        if(selectedRow!=-1){
            String courseId=courseTable.getValueAt(selectedRow, 1).toString();
            JPanel newPanel = new ManageLessonsPanel(courseId,ins,coursesDb);
            actionpanel.setLayout(new BorderLayout());
            actionpanel.add(newPanel, BorderLayout.CENTER);
        }
//        newPanel.add(new JLabel("View lessons"));
        else
            manageLessonsBtn.setEnabled(false);
    }//GEN-LAST:event_manageLessonsBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Confirm",JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose();
            LoginFrame login = new LoginFrame();
            login.setVisible(true);

        }
        else {return;}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new InstructorDashboard().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateCourse;
    private javax.swing.JPanel actionpanel;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton deleteCourse;
    private javax.swing.JButton editCourse;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageLessonsBtn;
    private javax.swing.JButton viewStudent;
    // End of variables declaration//GEN-END:variables
}
