/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Lesson;
/**
 *
 * @author malak
 */
public class LessonViewDialog extends javax.swing.JDialog {
    private Lesson l;
    private StudentDashboardFrame MainFrame;
    /**
     * Creates new form LessonViewPanel
     */
    public LessonViewDialog(StudentDashboardFrame MainFrame, Lesson l) {
        super(MainFrame, l.getTitle(), true);
        this.l=l;
        this.MainFrame=MainFrame;
        initComponents();
        lessonLabel.setText(l.getTitle());
        contentTextArea.setText(l.getContent());
        contentTextArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lessonLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTextArea = new javax.swing.JTextArea();
        takeQuizBtn = new javax.swing.JButton();

        lessonLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lessonLabel.setText("jLabel1");

        contentTextArea.setColumns(20);
        contentTextArea.setRows(5);
        jScrollPane1.setViewportView(contentTextArea);

        takeQuizBtn.setText("Take quiz");
        takeQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeQuizBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(lessonLabel)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(takeQuizBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lessonLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(takeQuizBtn)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void takeQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeQuizBtnActionPerformed
        // TODO add your handling code here:
        QuizPage quiz;
        quiz = new QuizPage((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
                true,l);
        quiz.setVisible(true);
        quiz.quizStart();
        this.dispose();
    }//GEN-LAST:event_takeQuizBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lessonLabel;
    private javax.swing.JButton takeQuizBtn;
    // End of variables declaration//GEN-END:variables
}
