/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Instructor;
import Backend.InstructorCourseManager;
import Backend.StudentProgressInCourse;
import Backend.Students;
import Backend.jsonFile;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author malak
 */
public class ManageLessonsPanel extends javax.swing.JPanel {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InstructorDashboard.class.getName());
    private Instructor ins;
    private InstructorCourseManager instructorManager;
    private String courseId;
    /**
     * Creates new form ManageLessonsPanel
     */
    public ManageLessonsPanel(String courseId, Instructor ins, jsonFile db) {
        this.courseId=courseId;
        this.ins=ins;
        this.instructorManager=new InstructorCourseManager(db);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        actionpanel = new javax.swing.JPanel();
        addLesson = new javax.swing.JButton();
        editLesson = new javax.swing.JButton();
        deleteLesson = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "ID", "Content"
            }
        ));
        jScrollPane1.setViewportView(lessonsTable);

        javax.swing.GroupLayout actionpanelLayout = new javax.swing.GroupLayout(actionpanel);
        actionpanel.setLayout(actionpanelLayout);
        actionpanelLayout.setHorizontalGroup(
            actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        actionpanelLayout.setVerticalGroup(
            actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        addLesson.setText("Add lesson");
        addLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonActionPerformed(evt);
            }
        });

        editLesson.setText("Edit lesson");
        editLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLessonActionPerformed(evt);
            }
        });

        deleteLesson.setText("Delete lesson");
        deleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(actionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteLesson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonActionPerformed
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow != -1) {
            String lessonId = lessonsTable.getValueAt(selectedRow, 1).toString();
            String currentTitle = lessonsTable.getValueAt(selectedRow, 0).toString();
            String currentDesc = lessonsTable.getValueAt(selectedRow, 2).toString();

            String newTitle = JOptionPane.showInputDialog(this, "Edit Title:", currentTitle);
            String newDesc = JOptionPane.showInputDialog(this, "Edit Description:", currentDesc);

            if (newTitle != null && newDesc != null) {
                instructorManager.addLesson(lessonId, newTitle, courseId, resourcesOptional, ins);
                lessonsTable.setValueAt(newTitle, selectedRow, 0);
                lessonsTable.setValueAt(newDesc, selectedRow, 2);
            }
        }
    }//GEN-LAST:event_addLessonActionPerformed

    private void editLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLessonActionPerformed
//        int selectedRow = courseTable.getSelectedRow();
//        if (selectedRow != -1) {
//            String courseId = courseTable.getValueAt(selectedRow, 1).toString(); // ID column
//            int confirm = JOptionPane.showConfirmDialog(this,
//                "Are you sure you want to delete this course?",
//                "Confirm Delete",
//                JOptionPane.YES_NO_OPTION);
//            if (confirm == JOptionPane.YES_OPTION) {
//                jsonFile.DeleteCourse(courseId,ins.getId());
//
//                ((DefaultTableModel)courseTable.getModel()).removeRow(selectedRow);
//                ArrayList<Students> students = jsonFile.getAllStudentinCourse(courseId);
//                for (int i = 0 ; i < students.size() ; i++)
//                {
//                    ArrayList<StudentProgressInCourse> enrolledCourses = students.get(i).getEnrolledCourses();
//
//                    for (int j = 0; j < enrolledCourses.size(); j++)
//                    {
//                        if (enrolledCourses.get(j).getCourseId().equals(courseId))
//                        {
//                            enrolledCourses.remove(j);
//                            break; // done
//                        }
//                    }
//
//                }
//
//                actionpanel.setVisible(false);
//                jsonFile.SAVE();
//            }
//        }
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow != -1) {
            String lessonId = lessonsTable.getValueAt(selectedRow, 1).toString();
            String currentTitle = lessonsTable.getValueAt(selectedRow, 0).toString();
            String currentContent = lessonsTable.getValueAt(selectedRow, 2).toString();

            String newTitle = JOptionPane.showInputDialog(this, "Edit Title:", currentTitle);
            String newContent = JOptionPane.showInputDialog(this, "Edit Content:", currentContent);

            if (newTitle != null && newContent != null) {
                instructorManager.editLesson(courseId, lessonId, newTitle, newContent, ins);
                lessonsTable.setValueAt(newTitle, selectedRow, 0);
                lessonsTable.setValueAt(newContent, selectedRow, 2);
            }
        }
    }//GEN-LAST:event_editLessonActionPerformed

    private void deleteLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLessonActionPerformed

        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow != -1) {
            String courseId = lessonsTable.getValueAt(selectedRow, 1).toString();
            ArrayList<Students> students = jsonFile.getAllStudentinCourse(courseId);

            StudentListDialog dlg = new StudentListDialog(this, true);
            dlg.setStudents(students);
            dlg.setVisible(true);
        }
    }//GEN-LAST:event_deleteLessonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionpanel;
    private javax.swing.JButton addLesson;
    private javax.swing.JButton deleteLesson;
    private javax.swing.JButton editLesson;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    // End of variables declaration//GEN-END:variables
}
