/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Instructor;
import Backend.InstructorCourseManager;
import Backend.InstructorLessonManager;
import Backend.StudentProgressInCourse;
import Backend.Students;
import Backend.jsonFile;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author malak
 */
public class ManageLessonFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InstructorDashboard.class.getName());
    private Instructor ins;
    private String courseId;
     private InstructorLessonManager instructorLessonManager;
    /**
     * Creates new form ManageLessonFrame
     */
    public ManageLessonFrame(String courseId, Instructor ins, jsonFile db) {
        this.courseId=courseId;
        this.ins=ins;
        this.instructorLessonManager=new InstructorLessonManager(db);
        initComponents();
        addQuizBtn.setEnabled(false);
        lessonsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) { // double click
                    int selectedRow = lessonsTable.getSelectedRow();
                    if (selectedRow != -1) 
                        addQuizBtn.setEnabled(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addQuizBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        actionpanel = new javax.swing.JPanel();
        addLesson = new javax.swing.JButton();
        editLesson = new javax.swing.JButton();
        deleteLesson = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addQuizBtn.setText("Add quiz");
        addQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuizBtnActionPerformed(evt);
            }
        });

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "ID", "Content"
            }
        ));
        jScrollPane1.setViewportView(lessonsTable);

        javax.swing.GroupLayout actionpanelLayout = new javax.swing.GroupLayout(actionpanel);
        actionpanel.setLayout(actionpanelLayout);
        actionpanelLayout.setHorizontalGroup(
            actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        actionpanelLayout.setVerticalGroup(
            actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        addLesson.setText("Add lesson");
        addLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonActionPerformed(evt);
            }
        });

        editLesson.setText("Edit lesson");
        editLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLessonActionPerformed(evt);
            }
        });

        deleteLesson.setText("Delete lesson");
        deleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(actionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addQuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteLesson)
                    .addComponent(addQuizBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuizBtnActionPerformed
        // TODO add your handling code here:
        CreateQuiz dialog = new CreateQuiz((Frame) this.getParent(), true);
        dialog.setLocationRelativeTo((Frame) this.getParent());
        dialog.setVisible(true);
    }//GEN-LAST:event_addQuizBtnActionPerformed

    private void addLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonActionPerformed

    }//GEN-LAST:event_addLessonActionPerformed

    private void editLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLessonActionPerformed

        //        int selectedRow = lessonsTable.getSelectedRow();
        //        if (selectedRow != -1) {
            //            String lessonId = lessonsTable.getValueAt(selectedRow, 1).toString();
            //            String currentTitle = lessonsTable.getValueAt(selectedRow, 0).toString();
            //            String currentContent = lessonsTable.getValueAt(selectedRow, 2).toString();
            //
            //            String newTitle = JOptionPane.showInputDialog(this, "Edit Title:", currentTitle);
            //            String newContent = JOptionPane.showInputDialog(this, "Edit Content:", currentContent);
            //
            //            if (newTitle != null && newContent != null) {
                //                instructorCourseManager.editLesson(courseId, lessonId, newTitle, newContent, ins);
                //                lessonsTable.setValueAt(newTitle, selectedRow, 0);
                //                lessonsTable.setValueAt(newContent, selectedRow, 2);
                //            }
            //        }
    }//GEN-LAST:event_editLessonActionPerformed

    private void deleteLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLessonActionPerformed
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow != -1) {
            String lessonId = lessonsTable.getValueAt(selectedRow, 1).toString(); // ID column
            int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this lesson?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                instructorLessonManager.deleteLesson(courseId, lessonId, ins);

                ((DefaultTableModel)lessonsTable.getModel()).removeRow(selectedRow);
                actionpanel.setVisible(false);
                jsonFile.SAVE();
            }
        }
    }//GEN-LAST:event_deleteLessonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionpanel;
    private javax.swing.JButton addLesson;
    private javax.swing.JButton addQuizBtn;
    private javax.swing.JButton deleteLesson;
    private javax.swing.JButton editLesson;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    // End of variables declaration//GEN-END:variables
}
