/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frontend;

import Backend.Question;
import javax.swing.JOptionPane;
/**
 *
 * @author malak
 */
public class QuestionDialog extends javax.swing.JDialog {
    private Question q;
    private int selected=-1;
    /**
     * Creates new form QuestionDialog
     */
    public QuestionDialog(java.awt.Frame parent, Question q) {
        super(parent, true);
        this.q=q;
        initComponents();
        setupRadioButtons();
        questionTextArea.setText(q.getQuestion());
        optionOne.setText(q.getOptions()[0]);
        optionTwo.setText(q.getOptions()[1]);
        optionThree.setText(q.getOptions()[2]);
        optionFour.setText(q.getOptions()[3]);
    }
    private void setupRadioButtons() {
    javax.swing.ButtonGroup group = new javax.swing.ButtonGroup();
    group.add(optionOne);
    group.add(optionTwo);
    group.add(optionThree);
    group.add(optionFour);
}

    public int selected(){
        return selected;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionTwo = new javax.swing.JRadioButton();
        optionThree = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();
        optionFour = new javax.swing.JRadioButton();
        optionOne = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        optionTwo.setText("jRadioButton2");
        optionTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionTwoActionPerformed(evt);
            }
        });

        optionThree.setText("jRadioButton3");
        optionThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionThreeActionPerformed(evt);
            }
        });

        questionTextArea.setColumns(20);
        questionTextArea.setRows(5);
        jScrollPane1.setViewportView(questionTextArea);

        optionFour.setText("jRadioButton4");
        optionFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionFourActionPerformed(evt);
            }
        });

        optionOne.setText("jRadioButton1");
        optionOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionOneActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quiz");

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nextBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(optionOne)
                                .addComponent(optionTwo)
                                .addComponent(optionThree)
                                .addComponent(optionFour)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionThree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionFour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextBtn)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionOneActionPerformed
        // TODO add your handling code here:
        selected=0;
    }//GEN-LAST:event_optionOneActionPerformed

    private void optionTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionTwoActionPerformed
        // TODO add your handling code here:
        selected=1;
    }//GEN-LAST:event_optionTwoActionPerformed

    private void optionThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionThreeActionPerformed
        // TODO add your handling code here:
        selected=2;
    }//GEN-LAST:event_optionThreeActionPerformed

    private void optionFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionFourActionPerformed
        // TODO add your handling code here:
        selected=3;
    }//GEN-LAST:event_optionFourActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        if(selected==-1){
            JOptionPane.showMessageDialog(this, "Please select an answer before moving onto the next question.");
            return;
        }
        this.dispose();
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton optionFour;
    private javax.swing.JRadioButton optionOne;
    private javax.swing.JRadioButton optionThree;
    private javax.swing.JRadioButton optionTwo;
    private javax.swing.JTextArea questionTextArea;
    // End of variables declaration//GEN-END:variables
}
