/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frontend;

import java.awt.Frame;
import Backend.Lesson;
import java.util.ArrayList;
import Backend.Quiz;
import Backend.StudentQuizAttempt;
import Backend.Students;
import Backend.jsonFile;
import javax.swing.JOptionPane;
/**
 *
 * @author malak
 */
public class QuizPage extends javax.swing.JDialog {

    private Quiz quiz;
    private ArrayList<Integer> answers;
    private Students stu;
    /**
     * Creates new form QuizPage
     */
    public QuizPage(Frame parent, boolean modal, Quiz quiz, Students stu) {
        super(parent, modal);
        this.quiz=quiz;
        this.answers=new ArrayList<>();
        this.stu=stu;
        initComponents();
        this.quizStart();
    }
    public final void quizStart(){
        for(int i=0; i<quiz.getQuestions().size();i++){
            QuestionDialog q=new QuestionDialog((Frame) this.getParent(), quiz.getQuestions().get(i));
            q.setLocationRelativeTo(this.getParent());
            q.setVisible(true);
            answers.add(q.selected());
        }
        StudentQuizAttempt attempt=new StudentQuizAttempt(stu.getId(), quiz.getQuizid(), quiz, answers);
        jsonFile.ADDattemptStudent(stu.getId(), attempt);
        int score=attempt.getScore();
        boolean passed=attempt.isPassed();
        JOptionPane.showMessageDialog(this, "Done!\nScore: "+score+"/"+quiz.getQuestions().size()+"\nPassed: "+(passed?"Yes":"No"));
        this.dispose();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quiz");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
