/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;
import Backend.Course;
import Backend.StudentProgressInCourse;
import Backend.Students;
import Backend.jsonFile;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author DELL
 */


public class ViewEnrolledCourses extends javax.swing.JPanel {
private Students currentStudent;
private JTabbedPane tabs;
private StudentDashboardFrame MainFrame;
    /**
     * Creates new form ViewEnrolledCourses
     */
    public ViewEnrolledCourses(Students currentStudent, JTabbedPane tabs,StudentDashboardFrame MainFrame) {
        this.currentStudent = currentStudent;
        this.tabs = tabs;
        this.MainFrame = MainFrame;
        initComponents();
        addLIST();
        
       
        
           }
    public void Refrresh(Students currentStudent){
        this.currentStudent = currentStudent;
    ArrayList<StudentProgressInCourse> enrolled = currentStudent.getEnrolledCourses();
    addLIST();
    }
    private void addLIST(){
      //this.enrolledCoursesList = new javax.swing.JList<>();
        
     ArrayList<StudentProgressInCourse> enrolledCourses = currentStudent.getEnrolledCourses();
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (int i = 0; i < enrolledCourses.size(); i++) {
            Course c = jsonFile.containsCourse(enrolledCourses.get(i).getCourseId());
            listModel.addElement(c.getTitle()); //hanhot kol course
        }
        
        this.enrolledCoursesList.setModel(listModel);
       
        this.enrolledCoursesList.addMouseListener(new MouseAdapter() {
        @Override
               public void mouseClicked(MouseEvent e) {
                    if (e.getClickCount() == 2) { 
                        String selectedTitle = enrolledCoursesList.getSelectedValue();
                        if (selectedTitle != null) {
                            Course selectedCourse = null;
                            for (int i = 0; i < enrolledCourses.size(); i++) {
                             Course c = jsonFile.containsCourse(enrolledCourses.get(i).getCourseId());
                           if (c.getTitle().equals(selectedTitle)) {
                           selectedCourse = c;
                                break;
                                
                                    }
                      }if (selectedCourse != null) {
                        ViewLessons vl = new ViewLessons(selectedCourse,currentStudent,MainFrame);
                        int viewLessonsIndex = tabs.indexOfTab("View Lessons");
                        if(viewLessonsIndex  == -1){
                        tabs.addTab("View Lessons",vl);
                        viewLessonsIndex = tabs.indexOfTab("View Lessons");
                        
                        }
                        else {
                        tabs.setComponentAt(viewLessonsIndex, vl);
                        }
                    //tabs.setComponentAt(viewLessonsIndex, vl);
                    tabs.setSelectedIndex(viewLessonsIndex);
                    }
                        }
                    }
               }
        });
        
    
    
    }
   
               

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        enrolledCoursesList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        enrolledCoursesList.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        enrolledCoursesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lesson 1", "Lesson 2", "Lesson 3", "Lesson 4", "Lesson 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(enrolledCoursesList);

        jLabel1.setFont(new java.awt.Font("Dutch801 Rm BT", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View enrolled lessons");

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Confirm",JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            SwingUtilities.getWindowAncestor(this).dispose();
            LoginFrame login = new LoginFrame();
            login.setVisible(true);

        }
        else {return;}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> enrolledCoursesList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
