/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;
import Backend.Students;
import Backend.Course;
import Backend.Lesson;
import Backend.StudentProgressInCourse;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author DELL
 */
public class ViewLessons extends javax.swing.JPanel {

    /**
     * Creates new form ViewLessons
     */
    private   Course course;
    private Students currentStudent;
    private JButton backButton;
    private StudentDashboardFrame MainFrame;

    
     private StudentProgressInCourse studetProgressInCourse;
     
    
    public ViewLessons(Course course, Students currentStudent,StudentDashboardFrame MainFrame) {
        
          initComponents();
          this.course = course;
          this.currentStudent=currentStudent;
          this.MainFrame = MainFrame;
          this.studetProgressInCourse = currentStudent.SearchINEnrolled(course.getCourseId());
          progressBar.setValue((int) studetProgressInCourse.getOverallProgress());
          if(this.studetProgressInCourse  == null){
          ArrayList<String> lessonIDs = new ArrayList<>();
          for (Lesson l : course.getLessons()) {
          lessonIDs.add(l.getLessonID());
          }
          currentStudent.newEnrollCourses(course.getCourseId(), lessonIDs);
          this.studetProgressInCourse = currentStudent.SearchINEnrolled(course.getCourseId());
          }
         

      loadLessons();
    }
    
    private void loadLessons(){
         //removeAll();
         ArrayList<Lesson> lessons = course.getLessons();
       
       DefaultListModel<String> listmodel = new DefaultListModel<>();
           for (int i = 0; i < lessons.size(); i++) {
           Lesson l = lessons.get(i);
           listmodel.addElement(l.getTitle());
           }
            lessonsList.setModel(listmodel);
            
             lessonsList.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                int index = lessonsList.getSelectedIndex();
                if (index != -1) {
                    Lesson selected = lessons.get(index);
                   javax.swing.JDialog lDialog = new javax.swing.JDialog(MainFrame, selected.getTitle(), true);
                lDialog.setSize(600, 400);
                lDialog.setLocationRelativeTo(MainFrame);

                LessonView l = new LessonView(selected,MainFrame);
                lDialog.add(l);

                lDialog.setVisible(true);
                   
                    
                 
                     
                    
                    
            }
            }
                     }
             });

           
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsList = new javax.swing.JList<>();
        lessonstxt = new javax.swing.JLabel();
        markdoneButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        progressBar.setMaximum(100);
        


        lessonsList.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 18)); // NOI18N
        lessonsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lesson 1", "Lesson 2", "Lesson 3", "Lesson 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lessonsList);

        lessonstxt.setFont(new java.awt.Font("Dutch801 Rm BT", 3, 24)); // NOI18N
        lessonstxt.setText("Lessons:");

        markdoneButton.setText("Mark done");
        markdoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markdoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessonstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(markdoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lessonstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(markdoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void markdoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markdoneButtonActionPerformed
        int index = lessonsList.getSelectedIndex();
        
        
             if(index != -1 )
           {
            ArrayList<Lesson> lessons = course.getLessons();
            Lesson lesson = lessons.get(index);
            
            float prog =  currentStudent.UpdateLesson(course.getCourseId(),lesson.getLessonID()); //n3mlha mark enaha done
            
            DefaultListModel<String> listModel = (DefaultListModel<String>) lessonsList.getModel();
            listModel.set(index, lesson.getTitle() + " ✅"); //nktb gmbha enaha done
            
           // float prog = currentStudent.UpdateLesson(TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY);
            int progress = (int) (prog*100);
            
             progressBar.setValue(progress); 
               

            }
    }//GEN-LAST:event_markdoneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lessonsList;
    private javax.swing.JLabel lessonstxt;
    private javax.swing.JButton markdoneButton;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
